import { useId } from 'react';
import { Sparkles, TrendingUp } from 'lucide-react';
import { formatDate } from '../lib/format';
import { sourceInfo } from '../lib/signals';
import type { CompanyAiEnrichment } from '../types';

/** The stored LLM write-up of a company's public signals, labeled as AI-generated. */
export function SummaryReport({ report }: { report: CompanyAiEnrichment }) {
  const titleId = useId();
  const sources = [...new Set(report.evidenceSources.map((s) => sourceInfo(s).name))];

  return (
    <section className="summary-report" aria-labelledby={titleId}>
      <h3 className="section-title summary-title" id={titleId}>
        Summary report
        <span className="ai-badge">AI</span>
      </h3>
      <div className="summary-body">
        <p className="summary-text">{report.summary}</p>
        {report.momentumSummary && (
          <p className="summary-momentum">
            <TrendingUp size={18} aria-hidden="true" />
            <span>{report.momentumSummary}</span>
          </p>
        )}
        {report.keySignals.length > 0 && (
          <ul className="summary-signals" aria-label="Key signals">
            {report.keySignals.map((signal, i) => (
              <li key={i}>{signal}</li>
            ))}
          </ul>
        )}
        <p className="summary-meta">
          <Sparkles size={14} aria-hidden="true" />
          <span>
            Generated by AI from {sources.length ? sources.join(', ') : 'public'} records on{' '}
            {formatDate(report.generatedAt)}. Not investment advice.
          </span>
        </p>
      </div>
    </section>
  );
}
